<a href="https://colab.research.google.com/github/josefa-santana/topicosEspeciaisII/blob/main/exNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Josefa Santana - GU3011976**


#### EX - 1

In [2]:
import numpy as np

#### EX - 2

In [ ]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### EX - 3

In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### EX - 4

In [ ]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### EX - 5

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### EX - 6

In [ ]:
np.arange(10, 52, +2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### EX - 7

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### EX - 8

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### EX - 9

In [13]:
np.random.rand()

0.7334064249395488

#### EX - 10

In [18]:
n = 100
%timeit np.random.normal(size=n)

8.89 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
np.random.rand(25)

array([0.87471101, 0.23417235, 0.72999804, 0.71595224, 0.8748557 ,
       0.8429043 , 0.42087134, 0.48326468, 0.60836692, 0.74438385,
       0.87342543, 0.35868462, 0.64137176, 0.61575342, 0.56483416,
       0.97838254, 0.03412562, 0.80475049, 0.41768089, 0.27701297,
       0.23461364, 0.15561229, 0.42184388, 0.50758383, 0.4433789 ])

#### EX - 11

In [32]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### EX - 12

In [34]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### EX - 13

In [36]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [71]:
arr = mat

In [82]:
arr2 = arr[-3:,1:]
arr2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### EX - 14

In [80]:
arr[3,4]

20

#### EX - 15

In [122]:
arr[:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

#### EX - 16

In [127]:
arr[-1:]

array([[21, 22, 23, 24, 25]])

#### EX - 17

In [128]:
arr[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### EX - 18

In [130]:
arr.sum()

325

#### EX - 19

In [131]:
arr.std()


7.211102550927978

#### EX - 20

In [134]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])